import type { Listing } from "./types";

/**
 * Seed listings used when no Supabase project is connected, so the app is
 * fully browsable out of the box. Mirrors the shape of the `listings` table in
 * supabase/migrations/0001_init.sql.
 */
export const MOCK_LISTINGS: Listing[] = [
  {
    id: "sto-park-sodermalm",
    title: "Bevakad p-plats på Södermalm",
    category: "parking",
    city: "Stockholm",
    area: "Södermalm",
    pricePerMonth: 1850,
    sizeLabel: "Personbil, upp till 5 m",
    covered: false,
    evCharging: true,
    access247: true,
    consentVerified: true,
    rating: 4.9,
    reviewCount: 27,
    hostName: "Elin",
    lat: 59.3141,
    lng: 18.0711,
    description:
      "Egen hyrd p-plats i bevakat område, 3 min från Medborgarplatsen. Jag pendlar och behöver den bara vissa dagar. Elbilsladdning finns via fastigheten.",
    swatch: "#2f6f57",
    createdAt: "2026-07-10T09:00:00Z",
  },
  {
    id: "sto-garage-vasastan",
    title: "Varmgarage i Vasastan",
    category: "garage",
    city: "Stockholm",
    area: "Vasastan",
    pricePerMonth: 2600,
    sizeLabel: "Enskild garageplats",
    covered: true,
    evCharging: true,
    access247: true,
    consentVerified: true,
    rating: 5.0,
    reviewCount: 12,
    hostName: "Johan",
    lat: 59.3434,
    lng: 18.0492,
    description:
      "Uppvärmd garageplats i bostadsrättsförening. Föreningen tillåter andrahandsuthyrning — samtycke uppladdat. Nyckelbricka lämnas via app.",
    swatch: "#37506b",
    createdAt: "2026-07-12T14:30:00Z",
  },
  {
    id: "sto-storage-kista",
    title: "Torrt förråd 6 m² i Kista",
    category: "storage",
    city: "Stockholm",
    area: "Kista",
    pricePerMonth: 750,
    sizeLabel: "6 m² (ca 15 m³)",
    covered: true,
    evCharging: false,
    access247: true,
    consentVerified: false,
    rating: 4.6,
    reviewCount: 8,
    hostName: "Amira",
    lat: 59.4029,
    lng: 17.9445,
    description:
      "Rent och torrt förråd i källarplan. Perfekt för säsongsförvaring, möbler eller lådor. Kodlås, egen ingång.",
    swatch: "#6b5637",
    createdAt: "2026-07-14T08:15:00Z",
  },
  {
    id: "gbg-boat-lindholmen",
    title: "Båtplats vid Lindholmen",
    category: "boat",
    city: "Göteborg",
    area: "Lindholmen",
    pricePerMonth: 1400,
    sizeLabel: "Upp till 28 fot (LOA 8,5 m)",
    covered: false,
    evCharging: false,
    access247: true,
    consentVerified: true,
    rating: 4.8,
    reviewCount: 15,
    hostName: "Karin",
    lat: 57.7065,
    lng: 11.938,
    description:
      "Min båtplats står tom halva säsongen. Y-bom, el och vatten på bryggan. Klubben godkänner andrahandsupplåtelse denna säsong.",
    swatch: "#31606b",
    createdAt: "2026-07-09T18:45:00Z",
  },
  {
    id: "gbg-park-haga",
    title: "P-plats nära Haga",
    category: "parking",
    city: "Göteborg",
    area: "Haga",
    pricePerMonth: 1250,
    sizeLabel: "Personbil",
    covered: false,
    evCharging: false,
    access247: true,
    consentVerified: true,
    rating: 4.7,
    reviewCount: 19,
    hostName: "Oscar",
    lat: 57.6989,
    lng: 11.9585,
    description:
      "Hyrd markplats jag inte använder på vardagar. Gångavstånd till Järntorget och Linné. Enkel in- och utfart.",
    swatch: "#4a5f2f",
    createdAt: "2026-07-15T11:20:00Z",
  },
  {
    id: "sto-storage-hammarby",
    title: "Rymligt förråd i Hammarby Sjöstad",
    category: "storage",
    city: "Stockholm",
    area: "Hammarby Sjöstad",
    pricePerMonth: 1100,
    sizeLabel: "9 m² (ca 22 m³)",
    covered: true,
    evCharging: false,
    access247: false,
    consentVerified: true,
    rating: 4.9,
    reviewCount: 21,
    hostName: "Sofia",
    lat: 59.3033,
    lng: 18.0956,
    description:
      "Stort förråd med hyllsektioner. Tillgång 06–23 alla dagar. Bra för e-handelslager eller flyttförvaring.",
    swatch: "#5b426b",
    createdAt: "2026-07-11T16:05:00Z",
  },
  {
    id: "sto-garage-ostermalm",
    title: "Garageplats på Östermalm",
    category: "garage",
    city: "Stockholm",
    area: "Östermalm",
    pricePerMonth: 3200,
    sizeLabel: "Enskild plats i p-hus",
    covered: true,
    evCharging: true,
    access247: true,
    consentVerified: false,
    rating: 4.5,
    reviewCount: 6,
    hostName: "Henrik",
    lat: 59.3376,
    lng: 18.0846,
    description:
      "Central garageplats i uppvärmt p-hus. Elbilsladdare vid platsen. Uthyres då jag är utomlands under hösten.",
    swatch: "#6b3a3a",
    createdAt: "2026-07-16T07:40:00Z",
  },
  {
    id: "gbg-boat-saltholmen",
    title: "Bryggplats vid Saltholmen",
    category: "boat",
    city: "Göteborg",
    area: "Saltholmen",
    pricePerMonth: 1650,
    sizeLabel: "Upp till 31 fot",
    covered: false,
    evCharging: false,
    access247: true,
    consentVerified: true,
    rating: 5.0,
    reviewCount: 9,
    hostName: "Marcus",
    lat: 57.6567,
    lng: 11.7889,
    description:
      "Skyddad bryggplats i naturhamn. Djup 2,2 m. Perfekt utgångspunkt mot södra skärgården. Säsongsuthyrning.",
    swatch: "#2f5f6b",
    createdAt: "2026-07-08T13:10:00Z",
  },
];
